### ISSUE TITLE
Slow response to/ from hue

### ISSUE THREAD

**Issue by ThomasPoett** [Foddy/node-red-contrib-huemagic#100]
Hi all,

I'm observing very slow response at hue bridge.
e.g. a motion sensor or a switch triggers a light, it sometimes takes up to 2-5 sec before the light turns on. Furthermore, sometimes it do not react at all. I even see the Error 500 Socket issue.
I run it one raspymatic (raspberry with homematic).
Even I change the bridge a week ago and the issue stays the same. Also adding a second bridge and moving several bulbs the slow/none response issue stays.

Any clue what to do? All versions node-red and huemagic are up to date.

Cheers

**Comment by ThomasPoett** [comment]
no one any similar problems ? … or anything else we need figuring out why and how we can fix it

**Comment by antil697** [comment]
Same issue here. Motion sensor and all switches are pretty much useless now. I see these in my logs and wonder if this limits the polling of device states.

```
31 Oct 07:47:49 - [debug] [hue-bridge:Philips hue] TypeError: Cannot read property 'id' of undefined
    at EventEmitter.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-huemagic/red/hue-light.js:81:41)
    at EventEmitter.emit (events.js:198:13)
    at HueBridge.emitUpdates (/home/pi/.node-red/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:189:18)
    at scope.client.rules.getAll.then.then.then.updates (/home/pi/.node-red/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:68:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
31 Oct 07:47:51 - [debug] [hue-bridge:Philips hue] TypeError: Cannot read property 'length' of undefined
    at HueBridge.getUpdates (/home/pi/.node-red/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:94:25)
    at scope.client.rules.getAll.then.then.results (/home/pi/.node-red/node_modules/node-red-contrib-huemagic/red/hue-bridge-config.js:59:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ThomasPoett** [comment]
The behavior got a little better upon changing the Poll down to 1500. you can try this.

**Comment by gekkie** [comment]
Same here. Both my bridges are set to 3000. iConnectHue and the official app both see sensor being triggered and buttons being pushed but huemagic nothing. My guess would be hue has a problem or something is changing in the API and they are slowly rolling it out.

**Comment by PrintSeb** [comment]
Hi there
I have the same problem
the trigger time is between 2 and 5 seconds with the hue taps.
the hue app or homekit react immediately.
it is also perfect via homebridge and the response time is only at node-red.

**Comment by jeth222** [comment]
Hello,

Same issue for me. Lights turn on after long delays of up to 10 seconds once the Hue switch (button or dimmer) are pushed.

Those connected to Hue Bridge respond almost immediately.

**Comment by domiko96** [comment]
Hi there,
I use the group-node's output to control a self developed LED-Strip Controller via MQTT. I set the polling frequency down to 500ms but still it takes up to 15s until I see an output of the group-node if I change the group in the hue app or via Alexa. Is there any other way to decrease the reaction time beside the polling frequency in the bridge-settings?
Awesome project keep it going!

**Comment by Foddy** [comment]
The latest version uses the new SSE API from Philips Hue. HueMagic is now no longer pulling all the resources manually and responds to the updates directly if they have been sent from the bridge.

So, this issue should be fixed with the v4 :)

**Comment by domiko96** [comment]
Will test this.
@Foddy  Thanks for the great work!

**Comment by ziipzaaapM16A4** [comment]
i still have a very slow reaction.
often iget error 500 
i am trying to flash all lights in red but they are just switching partially and with a delay of 5 seconds.
