### ISSUE TITLE
Trouble with brightness payload and "Error: Philips Hue: 7, invalid value, null}, for parameter, transitiontime

### ISSUE THREAD

**Issue by shopro** [Foddy/node-red-contrib-huemagic#131]
After updating to 2.51 my payloads are having some issue. All the payloads worked fine before the update.

The payload of `{"brightness":0}` to turn off the light/group stopped working, it works if the int 0 is made a string "0", i.e `{"brightness":"0"}`. For any other brightness level int works. Using IKEA TRÅDFRI lights.

I get an error of "Error: Philips Hue: 7, invalid value, null}, for parameter, transitiontime" when a payload doesn't contain transitionTime property, this wasn't required before. The payload still gets processed normally even with the error.

**Comment by dongennl** [comment]
Having exact same issue... 
`"Error: Philips Hue: 7, invalid value, null}, for parameter, transitiontime"`

I did have transitiontime on the node, but either with or without I get the error.
Changing the parameter to a string did not help.

**Comment by dongennl** [comment]
Seems to only effect the 'extended on/off', the 'simple' one works fine.

**Comment by Foddy** [comment]
Thank you for this note. It should be fixed with 2.5.2!

**Comment by dongennl** [comment]
I'm afraid I'm still having issues with 2.5.2
(running on Docker, restarted container multiple times after upgrade)

This is still **ignored** by the hue-light node (though the error message is gone). The light does not turn off.
`msg.payload = {
    transitionTime: 20,
    on: false
  }
return msg;`

This **does** work:
`msg.payload = false
return msg;`

I need to figure out how to downgrade as all the lights in my house stay on now (3 motion sensors).
