### ISSUE TITLE
Random color not working

### ISSUE THREAD

**Issue by parasaurolophus** [Foddy/node-red-contrib-huemagic#167]
**Describe the bug**
Passing "random" as the value for "color" to a light node often fails. A few clicks on the `inject` node in the supplied flow shows that this long-standing bug is still present in 2.7.0.

**Flow to Reproduce**
```
[{"id":"c6b31d5b.017bb","type":"inject","z":"e483373d.aebfb8","name":"","topic":"","payload":"{\"on\":true,\"color\":\"random\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":320,"wires":[["c9bfe00e.6ec4f"]]},{"id":"c9bfe00e.6ec4f","type":"hue-light","z":"e483373d.aebfb8","name":"Floor Lamp","bridge":"d75a339d.b8a97","lightid":"9","colornamer":true,"skipevents":false,"x":310,"y":320,"wires":[[]]},{"id":"d75a339d.b8a97","type":"hue-bridge","z":"","name":"Hue Chez Nous","bridge":"192.168.86.21","key":"V7BxU8fI9bL2Pz7Mun4hBLG3g4CBTeaorkAc1uAH","interval":"3000","disableupdates":false}]
```

**Expected behavior**
Passing "random" as the value for "color" should work reliably.

**Screenshots**
![random-color-bug](https://user-images.githubusercontent.com/4588250/80716226-41225b00-8aac-11ea-8cef-5e1021500426.png)

**Please complete the following information:**
 - NodeRED version: 1.0.6
 - NodeJS version: 12.16.3
 - Device running NodeRED: Raspberry Pi 3B+ (Raspbian buster)

**Additional context**
In case it jogs any thoughts about a fix, here is the jsonata expression I use as a work-around for this bug:

```
(
   $r:=$floor($random()*256);
   $g:=$floor($random()*256);
   $b:=$floor($random()*256);
   $l:=$floor(0.2126*$r + 0.7152*$g + 0.0722*$b);
   {
       "on":true,
       "rgb":[$r,$g,$b],
       "brightnessLevel":$l
   }
)
```

**Comment by Foddy** [comment]
Do you have the same issues with “any” instead of “random” for the parameter?

**Comment by Foddy** [comment]
This weird error is finally fixed with the latest release. You can use "random" as well as "any" or "whatever" now as a color name to get a random color.

**Comment by parasaurolophus** [comment]
This error still occurs in 2.8.1

```
[
    {
        "id": "a3b87cd4.e67e9",
        "type": "inject",
        "z": "93ed4ec.16204b",
        "name": "8:{\"on\":true,\"color\":\"any\",\"brightness\":100}",
        "topic": "8",
        "payload": "{\"on\":true,\"color\":\"any\",\"brightness\":100}",
        "payloadType": "json",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 200,
        "y": 240,
        "wires": [
            [
                "cf7c76e6.8b8c48"
            ]
        ]
    },
    {
        "id": "cf7c76e6.8b8c48",
        "type": "hue-group",
        "z": "93ed4ec.16204b",
        "name": "",
        "bridge": "5a3e3ef6.ce10a",
        "groupid": "",
        "colornamer": true,
        "skipevents": false,
        "x": 450,
        "y": 240,
        "wires": [
            []
        ]
    },
    {
        "id": "5a3e3ef6.ce10a",
        "type": "hue-bridge",
        "z": "",
        "name": "Hue Chez Nous",
        "bridge": "192.168.86.21",
        "key": "vq9C66nmN2hrToNOMMgaxi90G8ExsyEHKDymxDKR",
        "interval": "3000",
        "disableupdates": false
    }
]
```
![huemagic-any-bug](https://user-images.githubusercontent.com/4588250/85557774-f3722c80-b5dc-11ea-9a7b-5ea12cd12e99.png)
![huemagic-version](https://user-images.githubusercontent.com/4588250/85558288-75625580-b5dd-11ea-846a-ef76fe4f72d7.png)
