### ISSUE TITLE
all nodes not working still update to 4.02

### ISSUE THREAD

**Issue by Donni1966** [Foddy/node-red-contrib-huemagic#264]
i have several buttons in my config. some Lights control and some animate nodes for light. Dimmer Switches and single buttons. both of them do not create a payload after press one of the buttons. before do the update, all works fine. 

it changes from bevor 4.0. with a private. version i have a node call hue Switches - is is away, now only the hue Botton ist there. i have to reconfigure my switches as buttons. Otherwise no start after update to 4.02 will start the flows. 

 - Node-RED version: 2.1.4
 - NodeJS version: 14.x.x.x not sure, is a docker
 - Relink users, now state is coming aft press the inject botton

so what i want to do: reading press form the botton long/short and so on, to start following nodes. or control lights and so on. 

i have two bridges in use. 

by the way: great tool, perfect work, i love this plugin. Hope this is only a small bug.

**Comment by Donni1966** [comment]
puh ... find the error. hav to setup a new user?! with link botton, than delay, now works. why ever?

**Comment by Foddy** [comment]
Nice! I am glad that the problem is solved :)

**Comment by Donni1966** [comment]
hmm .. not realy :-) i get now a state, press the (new) inject button, but still not reaction payload on press a button. any go this four or long or short.

**Comment by Donni1966** [comment]
install 4.03 - works!

but i have to deploy ale hue magic nodes one time again. But now is seems that all works fine. Thanx a lot for this fast support
