### ISSUE TITLE
Switch Node Errors

### ISSUE THREAD

**Issue by lespatots** [Foddy/node-red-contrib-huemagic#38]
I have a number of Switch nodes reading my Hue switch status. After the update to 1.4 I get a slew of errors as follows:
7/02/2018, 18:06:38node: MainSwitch
msg : error
"Error: Huejay: read ECONNRESET"
17/02/2018, 18:06:38node: KitchenCabinets
msg : error
"Error: Huejay: read ECONNRESET"
17/02/2018, 18:06:38node: Porch
msg : error
"Error: Huejay: read ECONNRESET"
17/02/2018, 18:06:40node: KitchenCabinets
msg : error
"Error: Huejay: read ECONNRESET"
17/02/2018, 18:06:40node: Porch
msg : error
"Error: Huejay: read ECONNRESET"
17/02/2018, 18:06:46node: Porch
msg : error
"Error: Huejay: read ECONNRESET"

The nodes themselves now sit in a 'waiting' state. Pressing the switches makes no difference. The nodes themselves are currently used to check the battery state, but I had planned to possibly read the last button pressed to activate other devices.

**Comment by Foddy** [comment]
Are you running the latest Hue Bridge firmware?

**Comment by lespatots** [comment]
Hi Foddy

Firmware is 1801260942, which I think is the latest. There is no update option available!

**Comment by lespatots** [comment]
I just created a new user on the bridge for these nodes and the errors have gone away 'I think'. It has left with two entries for the bridge. If I reselect the old one the problems reappear and I get these errors
8/02/2018, 12:26:44node: Hue 2
msg : error
"Error: Huejay: socket hang up"
Seems this might be a bridge problem?

**Comment by Foddy** [comment]
Fixed

**Comment by bausi2k** [comment]
Hi, still having a lot of "Error: Huejay: socket hang up"
Version 2.6.2 any Ideas?
